version: "3"
services:
  app:
    container_name: base_app
    # restart: always
    tty: true
    build:
      context: ./
      dockerfile: .docker/node/Dockerfile
      args:
        UID: 1000
        GID: 1000
    volumes:
      - "./:/var/www/html"
    ports:
      - "${PORT}:${PORT}"
    
  mongo:
    container_name: base_mongo
    ports:
    - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data:/data/db
    build:
      context: ./
      dockerfile: .docker/mongo/Dockerfile
      args:
        UID: 1000
        GID: 1000
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}